### ISSUE TITLE
Error con pip 10

### ISSUE THREAD

**Issue by leandro-gomez** [devartis/python-kong-client#13]
Desde [este commit](https://github.com/pypa/pip/commit/95bcf8c5f6394298035a7332c441868f3b0169f4), pip.req esta en `pip._internal.req`, lo cual hace que se rompa al intentar instalarlo con pip version 10.0.0b2.

Podria implementarse una solucion parecida a la que hicieron [aca](https://reviews.llvm.org/D45211?id=)

**Comment by poligarcia** [comment]
Solucionado en 5184233b6e9ea8467142a8d26bacf7a8e5869edc con algo similar: https://stackoverflow.com/a/49837302
